# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: checkpoints/Meta-Llama-3-8B/original/tokenizer.model

# Model
model:
  _component_: torchtune.models.llama3.lora_llama3_8b
  lora_attn_modules:
  - q_proj
  - v_proj
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: checkpoints/Meta-Llama-3-8B/original/
  checkpoint_files:
  - consolidated.00.pth
  recipe_checkpoint: null
  output_dir: checkpoints/Llama-3-LLaMS-kowiki/
  model_type: LLAMA3
resume_from_checkpoint: False

# Dataset
dataset:
  _component_: torchtuning.kowiki_dataset
  source: csv
  column: text
  data_files: data/20240520/kowikitext_20240520.csv
  max_seq_len: 2048
  split: train
seed: 31344
shuffle: True
batch_size: 1

# Optimizer
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.01
  lr: 0.0003

lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss

# Training
epochs: 10
max_steps_per_epoch: 200
gradient_accumulation_steps: 8
compile: True

# Logging
output_dir: torchtune-llams
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /tmp/lora_finetune_output
log_every_n_steps: 5

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: False

