# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: checkpoints/Llama-3-LLaMS-Instruct
  checkpoint_files: [
    meta_model_4.pt
  ]
  output_dir: checkpoints/Llama-3-LlaMS-Instruct
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: null

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: checkpoints/Meta-Llama-3-8B-Instruct/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "플라톤에 대해서 알려줘."
max_new_tokens: 2048
temperature: 0.0 # 0.8 and 0.6 are popular values to try
top_k: 300

quantizer: null
