# Config for QuantizationRecipe in quantize.py
#
# To launch, run the following command from root torchtune directory:
#    tune run quantize --config quantization

#
# Model arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: checkpoints/Llama-3-LLaMS-Instruct
  checkpoint_files: [
    meta_model_4.pt
  ]
  recipe_checkpoint: null
  output_dir: checkpoints/Llama-3-LlaMS-Instruct-quantized
  model_type: LLAMA3
  
device: cuda
dtype: bf16
seed: 1234

quantizer:
  _component_: torchtune.utils.quantization.Int4WeightOnlyQuantizer
  groupsize: 256
